### ISSUE TITLE
OnConstructionCancelled still called once (erroneously) after construction

### ISSUE THREAD

**Issue by schneeb** [snipplets/Dota-2-Building-Helper#10]
I noticed this when I added an ability refund to OnConstructionCancelled, which tends to mess with gameplay when buildings don't cost anything!
Not sure if anyone else was having this problem but I solved it by adding:

local builder = keys.caster
builder.work = nil

To OnConstructionStarted in abilities.lua

**Comment by musshorn** [comment]
Your timing is impeccable. Just fixed it, let me know if you have any problems.

**Comment by schneeb** [comment]
Works great thanks, I've got the shift queue ability cost issue that your already aware of!
