### ISSUE TITLE
Ability cost isn't charged with shift queue

### ISSUE THREAD

**Issue by schneeb** [snipplets/Dota-2-Building-Helper#12]
The first cast gets charged (when you press the ability) so subsequent casts aren't charged any abilitycost - I've only got buildings with goldcost so not sure if that is related?

**Comment by musshorn** [comment]
Pretty sure this is fixed now. I've added a OnPreConstruction call to the API which allows you to check the player has enough resources to build the unit before it gets built. This is called just before OnConstructionStarted and you can return false from it to cancel a build (which will in turn cause OnConstructionFailed to be called)

`abilities.lua` has been updated with  the bulk of how to implement it.

**Comment by schneeb** [comment]
Nice one, works great.
