### ISSUE TITLE
Ability Cooldown with Shift-Queueing

### ISSUE THREAD

**Issue by int128fly** [snipplets/Dota-2-Building-Helper#5]
Skip completly the cooldown and the cost while Shift-Queueing. Possible to fix on my end by charging the player only when tower is complete but the cooldown is a big issue, even if I manually put the cooldown on it skip it anyway.

Also it be nice if the cooldown be triggered only when clicking the emplacement.

**Comment by int128fly** [comment]
Just more info:

I don't want to charge the player when building is complete but when it start being build but the callback is ignore while buidling in Queue.

Here is actually code that I have:

``` lua
function Build(keys)
    local player = keys.caster:GetPlayerOwner()
    local player_id = player:GetPlayerID()
    local hero = PlayerResource:GetSelectedHeroEntity(player_id)
    local ability = keys.ability
    local ability_level = ability:GetLevel()

    hero:ModifyGold(ability:GetGoldCost(ability_level-1), true, 0)
    ability:EndCooldown()

    -- Check if player has enough resources here. If he doesn't they just return this function.

    BuildingHelper:AddBuilding(keys)

    print("build -> buidling requested")

    keys:OnBuildingPosChosen(function(vPos)
        --print("OnBuildingPosChosen")
        -- in WC3 some build sound was played here.
    end)

    keys:OnConstructionStarted(function(unit)
        print("Build -> Construction Start...")
        FindClearSpaceForUnit(keys.caster, keys.caster:GetAbsOrigin(), true)
        hero:ModifyGold(0 - ability:GetGoldCost(ability:GetLevel()-1), true, 0)
        ability:StartCooldown(ability:GetCooldown(ability_level))


        -- start the building with 0 mana.
        unit:SetMana(0)
    end)

    keys:OnConstructionCompleted(function(unit)
        -- Play construction complete sound.
        -- Give building its abilities
        -- add the mana
        print("Build -> Construction Complete!")
        unit:SetMana(unit:GetMaxMana())
    end)

    -- These callbacks will only fire when the state between below half health/above half health changes.
    -- i.e. it won't unnecessarily fire multiple times.
    keys:OnBelowHalfHealth(function(unit)
    end)

    keys:OnAboveHalfHealth(function(unit)

    end)

    keys:OnConstructionFailed(function( building )
        -- This runs when a building cannot be placed, you should refund resources if any. building is the unit that would've been built.
        print("Build -> Construction Failed!")
    end)

    keys:OnConstructionCancelled(function( building )
        -- This runs when a building is cancelled, building is the unit that would've been built.
        print("Build -> Construction Cancelled!")
    end)

    -- Have a fire effect when the building goes below 50% health.
    -- It will turn off it building goes above 50% health again.
    keys:EnableFireEffect("modifier_jakiro_liquid_fire_burn")
end
```

**Comment by rexex** [comment]
This helped me alot in the sense, that if Building helper bugged out, I would still spend money without the construction being completed, now this only deducts money when it is built. Thank you

**Comment by int128fly** [comment]
No problem, none the less this is still a big issue since the cooldown is being skip, would be nice to add the delay of the remaining cooldown to queue to the next building and trigger the cooldown.

**Comment by musshorn** [comment]
Just after some more details here.
So you've got a building with a cool down on when you can build it? So for example like a powerful tower in a TD to stop you spamming it? But if you're using shift-q it's ignoring the cooldown? would that be correct?

**Comment by int128fly** [comment]
Yes, shift-queue ignore the cooldown, the cost (mana or gold) and it does not trigger the cooldown either. The ability cooldown must be the delay between the next construction. Everything above can be fix by the user without touching building helper except for the cooldown being ignored.

**Comment by musshorn** [comment]
Ok I've just fixed this if you want to test it. The dark tower has a 10s cooldown and should call a `onConstructionFailed` if you try to build one while it's on cooldown

**Comment by int128fly** [comment]
sorry to re-open the topic, I was away for a long time but now I am back. The build should not get cancel if there is a cooldown, that is the point, it to make wait the unit before building the next building in queue (if in cooldown)

**Comment by musshorn** [comment]
No worries.
Well there's no real precedent set that I can think in wc3, so I guess I can have the worker wait till the building is no longer on cooldown before he moves on to the next one.

Edit: So would you prefer the worker stop at the last completed building then when the cooldown has completed, move to the next building and start? Or immediately move to the next building but don't start construction till it's off cooldown?
